service: scraper-service

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x


functions:
  hello:
    handler: scraper-service/dist/app.handler
    memorySize: 4096
    timeout: 60
    events:
      - http: ANY /
      - http: ANY /{proxy+}