name: Deploy Lambda

on:
  push:
    branches:
      - scraper-service

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        dir: ['scraper-service']
    steps:

    - uses: actions/checkout@v2
      
    - name: Use Node.js ${{ matrix.node-version }}
      working-directory: ${{ matrix.dir }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      working-directory: ${{ matrix.dir }}
      run: yarn

    - name: Rebuild the dist/ directory
      working-directory: ${{ matrix.dir }}
      run: |
        yarn build

    - name: serverless deploy
      working-directory: ${{ matrix.dir }}
      uses: serverless/github-action@master
      with:
        args: deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}